# coding=utf-8
"""
Django settings for esms project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import datetime
import logging

DEBUG = True

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIRNAME = os.path.dirname(__file__)

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tbkt',  # Or path to database file if using sqlite3.
        'USER': 'dba_user',
        'PASSWORD': 'tbkt123456',
        'HOST': '192.168.0.130',
        'PORT': '',  # Set to empty string for default. Not used with sqlite3.
    },
    'ketang': {
        'NAME': 'ketang',
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'dba_user',
        'PASSWORD': 'tbkt123456',
        'HOST': '192.168.0.130',
        'PORT': 3306
    },
    'ziyuan_new': {
        'NAME': 'ziyuan_new',
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'dba_user',  # Not used with sqlite3.
        'PASSWORD': 'tbkt123456',  # Not used with sqlite3.
        'HOST': '192.168.0.130',
        'PORT': 3306
    },
    'slave': {
        'NAME': 'tbkt',
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'dba_user',  # Not used with sqlite3.
        'PASSWORD': 'tbkt123456',  # Not used with sqlite3.
        'HOST': '192.168.0.130',  # Set to empty string for localhost. Not used with sqlite3.
        'PORT': 3306
    },
    'ziyuan_slave': {
        'NAME': 'ziyuan_new',
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'dba_user',  # Not used with sqlite3.
        'PASSWORD': 'tbkt123456',  # Not used with sqlite3.
        'HOST': '192.168.0.130',  # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '3306',  # Set to empty string for default. Not used with sqlite3.
    },
}

DATABASE_ROUTERS = ['account.router.MyAppRouter']

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'jv8dwsga=tf871=hi6#vdg#*0*7$$j!!iw*)%er0+mmb7mr&-&'
SESSION_COOKIE_AGE = 60*60*24
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_DOMAIN = ''
# Make this unique, and don't share it with anybody.

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = ['*']
# Application definition

INSTALLED_APPS = (
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    # 'django.contrib.messages',
    'django.contrib.staticfiles',
    'libs.models.account',
    'libs.models.ziyuan',
    'libs.models.mobile',
    'libs.models.tbkt',
    'libs.models.school_site',
    'libs.models.common',
    'libs.models.math',
    'libs.models.math2',
    'libs.models.english',
    'libs.models.english2',
    'libs.models.score',
    'libs.models.u_math',
    'libs.models.u_math2',
    'libs.models.u_english',
    'libs.models.u_english2',
    'libs.models.u_task',
    'libs.models.u_teacher',
    'libs.models.shared',
    'libs.models.class_manage',
    'libs.models.u_think',

    # custom installed app

)

AUTH_PROFILE_MODULE = 'account.Profile'

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    #'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'account.middleware.AuthenticationMiddleware',

    # custom middleware
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
)

ROOT_URLCONF = 'esms.urls'
USE_JINJA2 = 1

if USE_JINJA2:
    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.jinja2.Jinja2',
            'DIRS': [os.path.join(BASE_DIR, 'templates/')],
            'OPTIONS': {
                'environment': 'libs.tags.templatetags.jj2.Env'
            }
        },
    ]
else:
    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [os.path.join(BASE_DIR, 'templates/')],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                    'account.context_processors.settings',
                ],
            },
        },
    ]

PASSWORD_HASHERS = (
    'django.contrib.auth.hashers.SHA1PasswordHasher', # Insecure Hashes
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
)
# WSGI_APPLICATION = 'wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Etc/GMT-8'

USE_I18N = True

USE_L10N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

#MEDIA_URLROOT = 'http://192.168.99.100:808'#静态资源url
MEDIA_URLROOT = 'http://127.0.0.1:808'
DIR = 'media'
VERSION = "1.0"

# 文件上传目录
MEDIA_ROOT = os.path.join(BASE_DIR, 'upload/')

# 静态文件路径
MEDIA_SITE = os.path.join(BASE_DIR, 'site_media/')

# 动态模板文件
THEME_SITE = os.path.join(BASE_DIR, 'templates/')

# 静态模板
STATIC_SITE = os.path.join(BASE_DIR, "statictage")


# 文件上传密钥
UPLOAD_FILE_KEY_VALUE = 'bannei_upload'
# 文件服务器
FILE_WEB_URLROOT = 'http://file.tbkt.cn'
FLV_WEB_URLROOT = 'http://flv.xueceping.com'

WORD_AUDIO_API = '116.255.141.21'
RED5URL = '116.255.141.25:8035'

# 登录密钥
LOGIN_KEY_VALUE = 'tbkt_login'



HOST = "127.0.0.1"
#HOST = "192.168.99.100"
URLROOT = "http://%s:8072" % HOST
TBKT_TEACHER_WEB_ROOT = "http://%s:807" % HOST
TBKT_TEACHER_NEW_ROOT = "http://%s:8072" % HOST
TBKT_TEACHER_YY_WEB_ROOT = "http://%s:8071" % HOST
TBKT_STUDENT_WEB_ROOT = "http://%s:806" % HOST
TBKT_STUDENT_ENGLISH_ROOT ="http://%s:8000" % HOST
TBKTURLROOT = "http://%s:8000" % HOST



INTERNAL_IPS = ['127.0.0.1', ]

# 日志配置
LOGDIR = os.path.join(BASE_DIR, "log")
LOGFILE = datetime.datetime.now().strftime("%Y-%m-%d") + ".log"
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
                    datefmt='%a, %d %b %Y %H:%M:%S',
                    filename=os.path.join(LOGDIR, LOGFILE),
                    filemode='w')

# define a Handler which writes INFO messages or higher to the sys.stderr
fileLog = logging.FileHandler(os.path.join(LOGDIR, LOGFILE), 'w')
fileLog.setLevel(logging.DEBUG)
# set a format which is simpler for console use
formatter = logging.Formatter('%(asctime)s %(name)-12s: %(levelname)-8s %(message)s')
# tell the handler to use this format
fileLog.setFormatter(formatter)
# add the handler to the root logger
logging.getLogger('').addHandler(fileLog)
logging.getLogger('caching').setLevel(logging.INFO)

logging.info("tbkt_teacher.com Started")
